name: Create release with stub files

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build

    - name: Run
      run: ./teardownApiStubGenerator
      
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: v1.0.0-${{ steps.date.outputs.date }}
        tag_name: v1.0.0-${{ steps.date.outputs.date }}
        body_path: RELEASE.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: upload Lua stub file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./teardown.d.lua
        asset_name: teardown.d.lua
        asset_content_type: text/plain
        
    - name: upload Teal stub file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./teardown.d.tl
        asset_name: teardown.d.tl
        asset_content_type: text/plain
